sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli codeclimate-test-reporter istanbul'
  - 'bower install'
after_script:
  - 'codeclimate-test-reporter < ./coverage/report-lcov/lcov.info'
  - if [ "$TRAVIS_NODE_VERSION" = "0.12" ]; then grunt deploy; fi
